# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89fc5799d175cd6c9acfe05877513e4e447c5acf943a4493dbc0a749e8d99537da0a23d4ddaae47e841bd079d06350d21581450f74045b7621704d4659972613

test:
  secret_key_base: 9b542f0babe85b87a5e12933ebeb198800059cd2ee7104fe007ab9e2d800679079cfd8ac8c2142254a1902417f3e9d054cc5c70ddccfc87107661460c4b4ec86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
